version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
      - /app/priv/static
      - /app/assets/node_modules
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
