name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose services
        run: |
          docker-compose run --name test_container -e MIX_ENV=test -d web /bin/sh
          alias mix="docker exec test_container mix"
      
      - run: mix format --check-formatted --dry-run
      - run: mix credo --strict
      - run: mix sobelow -v
      - run: mix test
        
