name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose services
        run: docker-compose run --name test_container -e MIX_ENV=test -d web /bin/sh
      
      - name: Run mix format
        run: docker exec test_container mix format --check-formatted --dry-run

      - name: Run mix credo
        run: docker exec test_container mix credo --strict

      - name: Run mix sobelow
        run: docker exec test_container mix sobelow -v

      - name: Run mix test
        run: docker exec test_container mix coveralls.github
