name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: check format
        run: docker-compose run -T web mix format --check-formatted --dry-run

      - name: check consistency
        run: docker-compose run -T web mix credo --strict

      - name: check security
        run: docker-compose run -T web mix sobelow -v

      - name: run tests
        run: docker-compose run -T web mix test
        
