name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build docker image
        with:
          username: felipelincoln
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          image_name: prequest
          build_extra_args: "--build-arg MIX_ENV=dev --target build"
      
      - run: docker images
        
      - name: Start docker-compose services
        run: |
          docker-compose run --name test_container \
          -e MIX_ENV=test \
          -e CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} \
          -d web /bin/sh
      
      - name: Run mix format
        run: docker exec test_container mix format --check-formatted --dry-run

      - name: Run mix credo
        run: docker exec test_container mix credo --strict

      - name: Run mix sobelow
        run: docker exec test_container mix sobelow -v

      - name: Run mix test
        run: |
          docker exec test_container mix coveralls.json
          docker exec test_container "bash <(curl -s https://codecov.io/bash)"
