name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose services
        run: |
          docker-compose run --name test_container \
          -e MIX_ENV=test \
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e GITHUB_SHA=$GITHUB_SHA \
          -e GITHUB_REF=$GITHUB_REF \
          -e GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH \
          -e GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME \
          -d web /bin/sh
      - name: Copy event.json to container
        run: |
          docker exec test_container mkdir -p /home/runner/work/_temp/_github_workflow/
          docker cp event.json test_container:/home/runner/work/_temp/_github_workflow/
      
      - name: Run mix format
        run: docker exec test_container mix format --check-formatted --dry-run

      - name: Run mix credo
        run: docker exec test_container mix credo --strict

      - name: Run mix sobelow
        run: docker exec test_container mix sobelow -v

      - name: Run mix test
        run: docker exec test_container mix coveralls.github
